Update version to 4.6.2
coturn/coturn pull request #1174
Opened 2023-03-20 01:25 UTC by eakraly

Update version number, generate authors and changelog files

2023-03-20 14:10 UTC, tyranron requested changes
I think changelog entries need careful revisiting to exclude redundant/irreleveant stuff from there.

Also, it's not clear why the previous changelist was wiped out, considering this PR targets `master` branch, so all the `master` changes should be relevant too.

2023-03-20 14:10 UTC, tyranron commented on ChangeLog
> +- Update Alpine to 3.16.4 version and Debian "bullseye" to 20230208 snapshot to fix CVE-2023-0286 (and friends) in Docker image (tyranron <tyranron@gmail.com>)
@eakraly this (and similar stuff) is not related to the Coturn itself, so is redundant in this changelog file.

2023-03-20 14:10 UTC, tyranron commented on ChangeLog
> +- Update CONTRIBUTING.md (Gustavo Garcia <gustavogb@gmail.com>)
@eakraly this also seems to be redundant as is not so useful for end-users.

2023-03-30 03:47 UTC, eakraly commented
@tyranron pls review again after the fixes. Thanks!

2023-04-02 10:49 UTC, ggarber commented
Great job!  Thank you for doing this Pavel.

If @tyranron can confirm the docker part should be ok with this change it looks good to me.

Changelist is long but I think we can create Release Notes manually with a summary of those to make sure people get the most important points.    Also we could start using conventional commits (feat: , chore:....) to make it easer to read if you are ok with it.

2023-04-03 17:29 UTC, tyranron approved these changes
@eakraly @ggarber I've removed some Docker-related stuff from the changelog being left, and now it seems fine 👍

2023-04-11 02:00 UTC, merged