changed int to uint16_t for port variables
coturn/coturn pull request #1436
Opened 2024-02-21 01:12 UTC by WHYHD

### Approach:
- Search for variables named port or similar (i.e. _port)
- Swap **int** with **uint16_t** 
- If this effected a method signature search for calls and add **uint16_t** type casting  

This is same scale example to gain feedback on changing ports to unint16_t. I would like to make these changes everywhere so any feedback is welcome.

2024-02-21 02:39 UTC, eakraly requested changes
Left one comment to validate

2024-02-21 02:39 UTC, eakraly commented on src/apps/relay/dbdrivers/dbd_redis.c
> +      ret = redisLibeventAttach(base, co->host, (uint16_t)co->port, co->password, atoi(co->dbname));
Pls review if you can change the type to uint16_t in the struct rather than adding cast

2024-02-21 02:40 UTC, eakraly commented
Thank you @WHYHD for the contribution
The only comment would be to try and get the types right without casting - will be hard to get rid of them later

2024-03-20 20:23 UTC, jonesmz commented on src/apps/relay/dbdrivers/dbd_redis.c
> +        co->port = atoi(seq + 1);
don't you need a cast to uint16_t to avoid the compiler warning about precision loss?

2024-03-20 20:23 UTC, jonesmz commented on src/apps/relay/dbdrivers/dbd_redis.c
> +          port = (co->port);
parenthesis aren't needed here anymore.

2024-07-12 17:51 UTC, closed without merging